### ISSUE TITLE
Portuguese (Portugal) Translation Progress

### ISSUE THREAD

**Issue by tesseralis** [reactjs/pt-PT.reactjs.org#1]
## Maintainer List

* @telmogoncalves
* @fjoshuajr
* @jbarradas
## For New Translators

To translate a page:

1. Check that no one else has claimed your page in the checklist and comments below.
2. Comment below with the name of the page you would like to translate. **Please take only one page at a time**.
3. Clone this repo, translate your page, and submit a pull request!

Before contributing, read the glossary and style guide (once they exist) to understand how to translate various technical and React-specific terms.

Please be prompt with your translations! If you find that you can't commit any more, let the maintainers know so they can assign the page to someone else.

And please join us in Slack (https://rt-slack-invite.herokuapp.com), we have dedicated channels for each translation team. You might seek help there, either with translation processes or suggestions of words/sentences you might have been struggling with.

## For Maintainers

When someone volunteers, edit this issue with the username of the volunteer, and with the PR. Ex:

* [ ] Home Page (@tesseralis) #1

When PRs are merged, make sure to mark that page as completed!

## Core Pages

To do before releasing as an "official" translation. **Please translate these pages first.**

* [ ] Home Page (@nelsonmfinda)
* [ ] Tutorial

### Basics

* [x] Hello World (@jbarradas) #6 
* [ ] Introducing JSX
* [x] Rendering Elements (@fjoshuajr) #14
* [x] Components and Props (@fjoshuajr) #17
* [ ] State and Lifecycle (@antonio-rodrigues)
* [x] Handling Events (@fjoshuajr) #47
* [ ] Conditional Rendering
* [ ] Lists and Keys (@flowck)
* [ ] Forms
* [ ] Lifting State Up
* [x] Composition vs Inheritance (@fjoshuajr) #46
* [ ] Thinking in React

### API Reference

* [ ] React
* [ ] React.Component
* [x] ReactDOM (@jbarradas) #13 
* [x] ReactDOMServer (@fjoshuajr) #7 
* [ ] DOM Elements
* [ ] SyntheticEvent
* [ ] Test Utilities
* [ ] Shallow Renderer
* [x] Test Renderer (@fjoshuajr) #21
* [x] JS Environment Requirements (@fjoshuajr) #16
* [ ] Glossary

### Navigation

These are the navigation links that appear in the sidebar. Possibly wait until
the corresponding sections are translated to do these.

* [x] tutorial/nav.yml (@reinaldosimoes) #55
* [x] docs/nav.yml (@reinaldosimoes) #53

## Next Steps

These are the next most important translations, ordered by importance:

### Installation

* [x] Getting Started (@telmogoncalves) [#3](https://github.com/reactjs/pt-PT.reactjs.org/pull/3)
* [ ] Add React to a Website
* [ ] Create a New React App
* [x] CDN Links (@telmogoncalves) [#11](https://github.com/reactjs/pt-PT.reactjs.org/pull/11)

### Hooks

Everyone is hooked on hooks! People are really excited about these, and it would be great for them to be translated.

* [ ] Introducing Hooks
* [ ] Hooks at a Glance
* [ ] Using the State Hook
* [ ] Using the Effect Hook
* [ ] Rules of Hooks
* [ ] Building Your Own Hooks
* [ ] Hooks API Reference
* [ ] Hooks FAQ

### Warnings

These are the pages that you get when you click the links in the console (e.g. https://reactjs.org/warnings/dont-call-proptypes.html). People tend to search these, so **please don't translate the error message itself**.
 
* [ ] dont-call-proptypes
* [ ] invalid-aria-prop
* [ ] invalid-hook-call-warning
* [ ] legacy-factories
* [ ] refs-must-have-owner
* [ ] special-props
* [ ] unknown-prop

### Advanced Guides

* [x] Accessibility (@xiCO2k) #62 
* [x] Code-Splitting (@reinaldosimoes) #52
* [ ] Context
* [ ] Error Boundaries
* [ ] Forwarding Refs
* [ ] Fragments
* [ ] Higher-Order Components
* [ ] Integrating with Other Libraries
* [ ] JSX In Depth
* [ ] Optimizing Performance
* [ ] Portals
* [ ] React Without ES6
* [ ] React Without JSX
* [ ] Reconciliation
* [ ] Refs and the DOM
* [ ] Render Props
* [ ] Static Type Checking
* [ ] Strict Mode
* [ ] Typechecking With PropTypes
* [ ] Uncontrolled Components
* [ ] Web Components

### FAQ

* [x] APIs and AJAX (@fjoshuajr) #40
* [x] Babel, JSX, and Build Steps (@fjoshuajr) #12
* [x] Passing Functions to Components (@fjoshuajr) #41
* [x] Component State (@fjoshuajr) #43
* [ ] Styling and CSS (@luisdiogo2071317) #25
* [x] File Structure (@fjoshuajr) #44
* [x] Versioning Policy (@fjoshuajr) #45
* [x] Virtual DOM and Internals (@fjoshuajr) #42

### Contributing

Priority: Low

* [ ] How to Contribute
* [ ] Codebase Overview
* [ ] Implementation Notes
* [ ] Design Principles

### Components

Components in `src/components` that have some text in them.

* [x] CodeEditor (@fjoshuajr) #39
* [x] CodeExample (@fjoshuajr) #39
* [x] ErrorDecoder (@fjoshuajr) #5
* [x] LayoutFooter (@fjoshuajr) #39
* [x] LayoutHeader (@fjoshuajr) #39
* [x] MarkdownPage (@fjoshuajr) #39

## Additional Translations

These are not the primary translation targets.

* [ ] Blog
* [ ] Community

**Comment by telmogoncalves** [comment]
@fjoshuajr @jbarradas uma questão que me surgiu agora que comecei a traduzir. Eu estou a traduzir de modo a dirigir-me a **tu** e não a **voçê**.

#### Exemplo básico:
- Experiment**a** React
- Experiment**e** React

Que abordagem devemos usar?

**Comment by fjoshuajr** [comment]
Sou a favor de Experimente.

**Comment by fjoshuajr** [comment]
E como já começaste a traduzir, existem alguns pontos que temos que discutir.

- Palavras que podem ou não ser traduzidas.
	- Ex. state, high-order components, render, props, wrapper, etc.
- Todas palavras nos títulos da versão inglesa começam com maiúsculas (mantemos essa forma ou apenas capitalizamos a primeira palavra?)
	- Ex. 'Learn Once, Write Anywhere', 'A Component Using External Plugins'

**Comment by telmogoncalves** [comment]
@fjoshuajr vou alterar então, que eu estava a ir com a abordagem **tu**.

Em relação às palavras que podem ou não ser traduzidas concordo contigo, eu já vi algures alguém a falar sobre isso, quando encontrar meto aqui.

**Comment by telmogoncalves** [comment]
E também acho que devemos capitalizar a primeira palavra nos títulos.

**Comment by telmogoncalves** [comment]
I’ve created a Slack called react-translations. If you guys think it’s easier to discuss some topics there let me know and I’ll invite you 👍

**Comment by tesseralis** [comment]
@telmogoncalves is that slack for just Portuguese or for all translators? :P

**Comment by telmogoncalves** [comment]
All translators 😊 I was thinking about creating channels for the different languages.

**Comment by fjoshuajr** [comment]
@telmogoncalves if you do, use Discord instead. Slack has a 10K message limit in their free tier.

**Comment by telmogoncalves** [comment]
@fjoshuajr you think the 10k limit will be a problem?

**Comment by telmogoncalves** [comment]
@fjoshuajr @jbarradas thoughts?

**Comment by tesseralis** [comment]
How about we bring it up with the larger github group? (https://github.com/orgs/reactjs/teams/reactjs-org-localization)

I know a lot of the other languages have Slack / Discord / LINE / WhatsApp / Spectrum / Weibo already -- another channel of communication might make things more confusing.

**Comment by telmogoncalves** [comment]
That sounds good. I can ping them tomorrow morning if no one does.

**Comment by jbarradas** [comment]
I agree with a global slack (or whatever) with different channels for each language. This way we can exchange ideas between mantainers of different languages.

**Comment by tesseralis** [comment]
Technically, the github team is supposed to be that. I'd prefer relying on something within github itself so we don't require maintainers to get yet *another* account on something else. But I guess it's not really amenable to real-time chat.

**Comment by fjoshuajr** [comment]
> I agree with a global slack (or whatever) with different channels for each language. This way we can exchange ideas between mantainers of different languages.

+1

**Comment by telmogoncalves** [comment]
@fjoshuajr @jbarradas let's probably wait to see if it's OK with @tesseralis.

**Comment by jbarradas** [comment]
> @fjoshuajr @jbarradas let's probably wait to see if it's OK with @tesseralis.

Is this regarding a live chat? Just create a room for us (you can send invitation for slack). As she said, we should use GitHub the most we can, so things get in record and centralized.

We should use live chat just for quick questions/decisions between us. And try to put every important decision in Github some way. 

What you guys think?

**Comment by telmogoncalves** [comment]
> > @fjoshuajr @jbarradas let's probably wait to see if it's OK with @tesseralis.
> 
> Is this regarding a live chat? Just create a room for us (you can send invitation for slack). As she said, we should use GitHub the most we can, so things get in record and centralized.
> 
> We should use live chat just for quick questions/decisions between us. And try to put every important decision in Github some way.
> 
> What you guys think?

Yeah, we can do that. I'll be needing emails do add to slack.

**Comment by jbarradas** [comment]
barradas7@gmail.com

**Comment by nelsonmfinda** [comment]
> I’ve created a Slack called react-translations. If you guys think it’s easier to discuss some topics there let me know and I’ll invite you

Invite me :nerd_face:

**Comment by nelsonmfinda** [comment]
May I translate ***Home Page***?

**Comment by fjoshuajr** [comment]
@nelsonmfinda assigned to Home Page, thanks!

**Comment by tesseralis** [comment]
@telmogoncalves can you invite me to the slack and make me admin? Thinking about it, I think it's useful to have one central source for ephemeral discussion (the Polish group already started a spectrum, haha). I think I'll make it official and put it in the documentation / set up a way to automate adding people to the slack.

**Comment by nelsonmfinda** [comment]
> How about we bring it up with the larger github group? (https://github.com/orgs/reactjs/teams/reactjs-org-localization)
> 
> I know a lot of the other languages have Slack / Discord / LINE / WhatsApp / Spectrum / Weibo already -- another channel of communication might make things more confusing.

@tesseralis The link https://github.com/orgs/reactjs/teams/reactjs-org-localization _not found_ :disappointed:

**Comment by tesseralis** [comment]
@nelsonmfinda sorry, it's the _secret_ group available only to maintainers ^_^

**Comment by nelsonmfinda** [comment]
@tesseralis no problem.

**Comment by telmogoncalves** [comment]
> @telmogoncalves can you invite me to the slack and make me admin? Thinking about it, I think it's useful to have one central source for ephemeral discussion (the Polish group already started a spectrum, haha). I think I'll make it official and put it in the documentation / set up a way to automate adding people to the slack.

Invite sent.

**Comment by imflavio** [comment]
Can I have `Introducing Hooks` or is someone else doing it atm?

**Comment by jbarradas** [comment]
Guys, do it by priority, "Core Pages".

It says explicitly to "Please translate these pages first".

**Comment by imflavio** [comment]
Ahh got it, sorry about that.

**Comment by jbarradas** [comment]
> Ahh got it, sorry about that. I can't edit the 1st comment, so can you add me to `* Introducing JSX`?

Done! :)

Also, whenever possible, try to give priority to PR reviews (before translating new pages) so we don't stack them. Thanks for the support! :)

**Comment by telmogoncalves** [comment]
While translating take a look at [**Glossary**](https://github.com/reactjs/pt-PT.reactjs.org/issues/9), we'll be updating with more terms along the way.

**Comment by jbarradas** [comment]
@fjoshuajr @imflavio Can you please join us in Slack?
https://rt-slack-invite.herokuapp.com

We should handle some superficial discussions, translations suggestions, etc, in there. Instead of filling github with non-relevant comments. Appreciate! :)

**Comment by nelsonmfinda** [comment]
Hi everyone!
What tools are you using to translate documentation?
I would like to receive tips and suggestions.

**Comment by jbarradas** [comment]
@nelsonmfinda Only for context words and expressions I'm using Reverso and Linguee. And a lot of common sense. Sometimes the English sentence says more than we would say in Portuguese. Sometimes it says less than we would. So, we need to be careful to not translate things literally, step back, and think how would we say "that" in a fluent way.

If you need translation suggestions, please head to the slack channel ;)

**Comment by nelsonmfinda** [comment]
Thanks @jbarradas

**Comment by luisdiogo2071317** [comment]
Português/Portuguese:

(Eu removo este comentário, se tiver abusado de algum modo. Eu só queria pedir ajuda e ajudar, peço desculpa)

(Peço desculpa, por ser muito longo) Tem a tradução deste projeto num site chamado Crowdin  https://crowdin.com/ , Onde é feito a localização (explicação da diferença de localização de tradução https://content.lionbridge.com/the-difference-between-translation-and-localization-for-multilingual-website-projects-definitions/ ou https://www.vengaglobal.com/blog/translation-localization-difference/ (explica um pouco melhor)) deste projeto e é bem mais fácil de traduzir lá (imagens do Editor do Crowdin https://support.crowdin.com/online-editor/ (é a versão antiga que está nas imagens. Agora ficou bem melhor)). Eu já trabalho lá há um bom tempo e mesmo assim, falta tanto para acabar e daria muito jeito, se pudesse ter ajuda lá. Obrigado pela vossa atenção . Se quiserem ajudar, por favor, entrem por aqui https://translate.crowdin.com/project/react (podem entrar na vossa conta do google/github/facebook, etc e depois, irá voltar a essa página). Alguns dos exemplos de localização no Crowdin: NodeJs, Minecraft, GitLab, Hypixel, GommeHDNet (também server multiplayer de Minecraft ), CodeOrg (tutoriais de programação), Raspberry e muitos outros projetos para tradução/localização.
Basicamente, seria o que fazem aqui, mas com o Editor muito simples de usar e uma enorme facilidade de tradução (minha opinião, apenas isso).
Se não quiserem eu não me importo, eu sou, basicamente, o único que traduz para Português Europeu. De 259 757 palavras ainda só foram traduzidas 3 339 (1%).

Pequeno à parte: Eu também estou a traduzir o próprio site, ou seja, existe uma versão em português ainda não acabada (vai a 65%) e se quiserem ajudar de alguma forma https://pt.crowdin.com/project/react (fica em pt-pt com algumas coisas em inglês (ainda não foram traduzidas )) ou https://translate.crowdin.com/project/react (para ajudar na tradução do site (é uma espécie de tradução ao vivo, o que significa que podemos ver o que traduzimos enquanto escrevemos https://support.crowdin.com/in-context-localization/ ))

(Se leram a diferença entre localização e tradução irão perceber) Se repararem eu próprio fiz uma espécie localização deste comentário de português para inglês (um pouco de propósito)

Inglês/English:

(I will remove this comment if I abused in some way. I just wanted to ask for some help and to help, I'm really sorry)

(I'm really sorry for being so long)
 Has the translation of this project in a site called Crowdin https://crowdin.com/ . Where is made the localization (explanation of the difference in between localization and translation https://content.lionbridge.com/the-difference-between-translation-and-localization-for-multilingual-website-projects-definitions/ or https://www.vengaglobal.com/blog/translation-localization-difference/ (explains a little better) ) of this project and is much easier to translate there (images of the Crowdin's Editor https://support.crowdin.com/online-editor/ ( is the old version that are in the images and now is much better)) . I work there for a good time and even it, left so much to finish it and would be helpful if someone could help there. Thank you for your attention. If want to help, please come to here https://translate.crowdin.com/project/react (can enter with your google/github/facebook's account and then will return to that page). Some examples of localization's projects in Crowdin are NodeJs, Minecraft, GitLab, Hypixel, GommeHDNet (also a multiplayer server in Minecraft), CodeOrg (tutorials for coding), Raspberry and much other projects for translation/localization. 
Basicaly, it would be the same thing that do in here, but in a Editor that works really well and an easier way to translate (my opinion, just that) .
If don't want to help I won't mind it, I'm, basically, the only one that translates it into European Portuguese. From 259 757 words were only 3 3339 were translated (1%) .

Small apart: I'm as well translating the site itself, wich means that the site has a portuguese version (as much others) and still unfinished (is 65% done) and if want to help in some way can use https://pt.crowdin.com/project/react (will in pt-pt with some english words (aren't yet translated)) or https://translate.crowdin.com/project/react (to help to translate (is like a live translation wich means that we can see what we translate while we write https://support.crowdin.com/in-context-localization/ ))

( if have read the site of the site about the difference in between in localization and translation will understand ) If you notice I made a kind of localization of this comment from Portuguese to English (a bit in purpose)

**Comment by jbarradas** [comment]
@luisdiogo2071317 Boas. Don't take me wrong. Mas já fazer a tradução desta documentação de react não está fácil, quanto mais fazer outras.
Aqui (que eu saiba) ninguém é full-time translator. E só para este "projecto" precisamos de toda a ajuda possível (incluíndo a tua :p).
Quanto a React, acho que mais vale aguardares que a malta aqui traduza, depois é só pores lá. Até porque, se React vai ter documentação oficial traduzida, não vejo muito sentido em ter traduções por fora.
Good luck!

**Comment by luisdiogo2071317** [comment]
@jbarradas é que lá e aqui a diferença é que lá tem um Editor muito bom, enquanto que aqui, temos que depender imenso dos outros. Se, fores ver alguns dos projetos, por exemplo, o do React e testares algumas traduções, vais entender rapidamente. Eu já estou lá desde outubro de 2018 e tenho trabalhado em imensos projetos e daria jeito se alguém que já está habituado ou que já fez a tradução duma x página, aqui pôr a mesma coisa lá. É que, quando é-se o único a fazer um projeto de mais de 300 mil palavras fica muito difícil. E pôs a última foi mais para, por exemplo, uma frase ou palavra está incorreta dizem-me e corrijo e pronto. É assim, que lá funciona. E naquele texto enorme eu só falei muito superficialmente o que tem lá. E eu também estou a tratar do Support e só irá ficar em pt-pt quando chegar por volta dos 30% e ainda vai nos 13 %

**Comment by tesseralis** [comment]
Hi @luisdiogo2071317,

We actually were originally doing the translations on Crowdin but decided to switch to GitHub because we felt that it didn't suit our needs.

It seems that you are familiar with and prefer the Crowdin editor, but from talking to other developers, they tend to prefer GitHub because it's a system they're already familiar with. Pull requests and reviews are familiar to developers compared to whatever system Crowdin uses. There also doesn't seem to be any easy way to organize work on Crowdin, so there's no way to say which pages are the most important to be translated.

In addition, we ran into a lot of quality issues with the Crowdin translations. While some languages had good maintainers, others were not as well maintained and were inconsistent and full of errors. In fact, I looked at some of the Crowdin translations for projects you mentioned and found the same issues there. By doing this on GitHub with dedicated maintainers of each language, we can ensure that the community is empowered to keep their translations up-to-date and consistent. 

Another reason we're using GitHub is that many developers are motivated in contributing directly to the React organization as contributors, and creating translations is one of the most accessible ways to do that. Developers are generally more excited to work on translations here than on Crowdin!  In fact, within two months of *starting* this project we already have six completed translations!

And while you mention a lot of projects using Crowdin, I would also like to mention that Angular and Vue, two other popular frameworks, use this approach as well. I definitely think Crowdin is useful for a lot of projects, but in our case, our community has coding experience and is more comfortable using GitHub.

I hope that answers your questions, and I hope you will join us in translating the official React docs!

**Comment by luisdiogo2071317** [comment]
To be truthy I didn't know that and btw I am a programmer so for being in here or in Crowdin is the same. But at the same time I prefer more Crowdin where I can see if what I am translating it corresponds what should be instead of just translating. Crowdin is a lot more interactive in a lot ways. It has what is called Crowdin In-Context wich is a kind of live translating where we can see what we translate while we write. And it's possible to do it in the React site. I know that because Im a contributor of the Crowdin Support so I know a lot of things about Crowdin and I translate as well the Crowdin site itself.
Another thing is that in the md (Markdown) files we can see in live what we translate wich React project use.
And just a quick question does still use the Crowdin project or is kind of shut down?

**Comment by luisdiogo2071317** [comment]
In Crowdin basically is divided in 5 categories translators (can just suggest vote another suggestions) / proofreaders (can approve and suggest) / managers (can manage a translator to become proofreader/manager/banned and vice-versa) / owner (can do whatever he wants) / banned (can't do anything to the project). When a translator has an issue, the proofreader or other traslators talk to them in chat in the Editor wich can choose a topic of what his/her issue is and then the proofreader will help. When the proofreader approves something has to make sure that the translation corresponds to the right translation or to MTs TMS (Machine Translator) (Translation Memory) wich compares another translations and the translator can make sure what may use in some words or even the whole string and both use a percentage of how it looks with the string that is being translated (some links about TM and MT https://support.crowdin.com/translation-memory/ and https://support.crowdin.com/tm-auto-substitution/). Has as well some translators to help to choose the best translation for example google translator and now they have an own translator in beta version.
The project is as well divided in 3 topics public/private with request/ private. In the project has too some tabs to help

**Comment by tesseralis** [comment]
@luisdiogo2071317 the project is shut down. If you want to discuss this further, may I ask that you join [our Slack](https://rt-slack-invite.herokuapp.com/)?

**Comment by luisdiogo2071317** [comment]
@tesseralis I do want to help but I don't know much how to translate in here. By being proofreader of Crowdin site and a multiplayer server of Minecraft (GommeHDNet) I know well how to translate, but at the same time it may became confusing. I, basically, when I'm translating to English I translate in literal words as if I was going to speak into Portuguese

**Comment by jbarradas** [comment]
@luisdiogo2071317 You are still welcome to help. All translations go through a review process. However, literal translation is not the way to go, we should adapt to how the language is written.
If you want to start translating, just tell us which page and we'll reserve it to you.

**Comment by luisdiogo2071317** [comment]
@jbarradas When I speak and translate i do it in a way but when is really to translate I go for real

**Comment by luisdiogo2071317** [comment]
Eu estou a tentar fazer push de algo que já traduzi e não consigo fazê-lo e diz sempre que não tenho permissão.
I'm trying to do push in something that I translated and I can't do it and allways says that I don't have permission.

**Comment by luisdiogo2071317** [comment]
Posso já fazer logo duma vez todos do faq? ( exceto aquele que já posse)
Can I do all in faq? (except the one that was already taken)

**Comment by jbarradas** [comment]
@imflavio @flowck you both have claimed pages, but never submitted any PR. Should they remain claimed for you to translate or should we remove the claim? Thanks

**Comment by imflavio** [comment]
Remove mine please

**Comment by antonio-rodrigues** [comment]
Hi guys, native speaker here!
Maybe I can help in translating some pages.

I can pick up whatever's next on priority list (State and Lifecycle maybe?)
What rules should I be aware of, what tools are you using to facilitate translations, if any?

Thanks!

**Comment by fjoshuajr** [comment]
Olá @antonio-rodrigues, bem-vindo!

Sim, podes escolher `State and Lifecycle` (ou qualquer outro, esteja a vontade) mas confirma-me a tua escolha para que eu marque.

Alguma referência para ajudar-te no processo de tradução: https://github.com/reactjs/pt-PT.reactjs.org/issues/9

**Comment by antonio-rodrigues** [comment]
@fjoshuajr podes marcar então `State and Lifecycle`.
Já estive a rever as rules, vou tentar ajudar no que conseguir mediante a disponibilidade.

**Comment by jbarradas** [comment]
@antonio-rodrigues done. Quando tiveres um PR avisa para actualizarmos na lista.

**Comment by reinaldosimoes** [comment]
Tenho os seguintes PRs prontos para review:
`Code Splitting`: https://github.com/reactjs/pt-PT.reactjs.org/pull/52
`docs/nav.yml`: https://github.com/reactjs/pt-PT.reactjs.org/pull/53
`community/nav.yml`: https://github.com/reactjs/pt-PT.reactjs.org/pull/54
`tutorial/nav.yml`: https://github.com/reactjs/pt-PT.reactjs.org/pull/55

Achei por bem fazer os navs visto que funciona como uma single source of truth, em vez de ver cada página individualmente outra vez 😄

**Comment by danieljcafonso** [comment]
Hey everyone, native speaker here.
I would like to help if possible. Can I take and translate `Introducing Hooks`?

**Comment by telmogoncalves** [comment]
> Hey everyone, native speaker here.
> I would like to help if possible. Can I take and translate `Introducing Hooks`?

Go for it, we haven't been too active in the last few months though. Make sure you follow the _rules_ / _guidelines_.

Let's see if that changes this year.

**Comment by danieljcafonso** [comment]
> > Hey everyone, native speaker here.
> > I would like to help if possible. Can I take and translate `Introducing Hooks`?
> 
> Go for it, we haven't been too active in the last few months though. Make sure you follow the _rules_ / _guidelines_.
> 
> Let's see if that changes this year.

Thanks, will start working on it as soon as possible :smile:

**Comment by xiCO2k** [comment]
Boas pessoal finalizei a pagina da acessibilidade

**Comment by reinaldosimoes** [comment]
Code splitting ✔️  https://github.com/reactjs/pt-PT.reactjs.org/pull/52

**Comment by gaearon** [comment]
It looks like this translation has stalled, and is now very outdated.
I'm going to archive this repo, but if someone wants to pick up, please start a new effort.
